// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaRedeSocial.Infra.Dados;

#nullable disable

namespace MinhaRedeSocial.Infra.Migrations
{
    [DbContext(typeof(DadosContext))]
    partial class DadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Amigos.Amigo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Amigos.Amizade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AmigoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Amizades");
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Amigos.Amigo", b =>
                {
                    b.HasOne("MinhaRedeSocial.Domain.Models.Amigos.Amizade", "Amizade")
                        .WithOne("Amigo")
                        .HasForeignKey("MinhaRedeSocial.Domain.Models.Amigos.Amigo", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("MinhaRedeSocial.Domain.Models.Usuarios.Usuario", "Usuario")
                        .WithOne("Amigo")
                        .HasForeignKey("MinhaRedeSocial.Domain.Models.Amigos.Amigo", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Amizade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Amigos.Amizade", b =>
                {
                    b.HasOne("MinhaRedeSocial.Domain.Models.Usuarios.Usuario", "Usuario")
                        .WithMany("Amizades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Amigos.Amizade", b =>
                {
                    b.Navigation("Amigo")
                        .IsRequired();
                });

            modelBuilder.Entity("MinhaRedeSocial.Domain.Models.Usuarios.Usuario", b =>
                {
                    b.Navigation("Amigo")
                        .IsRequired();

                    b.Navigation("Amizades");
                });
#pragma warning restore 612, 618
        }
    }
}
